name: release
on:
  create:
    tags:
    - v*.*.*

jobs:
  release:
    name: Build
    # Windows Server 2019	windows-latest
    # Ubuntu 18.04	ubuntu-latestまたはubuntu-18.04
    # Ubuntu 16.04	ubuntu-16.04
    # macOS X Catalina 10.15	macos-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
      - name: Build
        env:
          GO111MODULE: on
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAGNAME=$(jq -r .ref "$GITHUB_EVENT_PATH")
          go run mage.go build
          ls -R release/
          mkdir bin
          GOBIN="$(pwd)/bin" go install github.com/tcnksm/ghr
          ./bin/ghr -n ${TAGNAME} -b "Release ${TAGNAME}" -draft ${TAGNAME} release/
